
IllustrationLogic.exe: IllustrationLogic.cpp
	dmc -Aer -L/SU:windows gdi32.lib comdlg32.lib winmm.lib IllustrationLogic.cpp

clean:
	rm IllustrationLogic.exe
	rm IllustrationLogic.map
	rm IllustrationLogic.obj

